# Generated by Django 4.0.6 on 2022-08-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=128)),
                ('group', models.IntegerField()),
                ('department', models.CharField(max_length=128)),
                ('professor', models.CharField(max_length=128)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('first_day', models.IntegerField(choices=[(0, 'شنبه'), (1, 'یکشنبه'), (2, 'دوشنبه'), (3, 'سه شنبه'), (4, 'چهارشنبه')])),
                ('second_day', models.IntegerField(blank=True, choices=[(0, 'شنبه'), (1, 'یکشنبه'), (2, 'دوشنبه'), (3, 'سه شنبه'), (4, 'چهارشنبه')], null=True)),
            ],
        ),
    ]
